my_site/activities/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.activity_list, name='list'),
    url(r'^availability/$', views.availability_page, name="availability"),
    url(r'(?P<activity_pk>\d+)/(?P<package_pk>\d+)/$', views.package_detail, name='package'),
    url(r'create_activity/$', views.activity_create, name='create_activity'),
    url(r'create_person/$', views.availability_create, name='create_person'),
    url(r'create_package/$', views.package_create, name='create_package'),
    url(r'(?P<pk>\d+)/$', views.activity_detail, name='detail'),
]

my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^activities', include('activities.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserved/$', views.reserved_view, name='reserved'),
    url(r'^contacts/$', views.contact_page, name='contacts'),
    url(r'^edit_page/$', views.edit_page, name='edit'),
    url(r'^$', views.home_page, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_site/activities/models.py
from django.db import models


# Create your models here.

snacks = (
    ('-- please select --', '- Please Select -'),
    ('pizzas', 'Pizzas'),
    ('chips', 'Chips'),
    ('ice cream', 'Ice Cream'),
    ('donuts', 'Donuts'),
    ('candies', 'Candies'),
    ('cookies', 'Cookies'),
    ('hot dogs', 'Hot Dogs'),
    ('hamburgers', 'Hamburgers')
)

drinks = (
    ('-- please select --', '- Please Select -'),
    ('coca cola', 'Coca Cola'),
    ('dr. pepper', 'Dr. Pepper'),
    ('pepsi', 'Pepsi'),
    ('fanta', 'Fanta'),
    ('sprite', 'Sprite'),
    ('apple juice', 'Apple Juice'),
    ('capri sun', 'Capri Sun')
)

activities = (
    ('-- please select --', '- Please Select -'),
    ('movie night', 'Movie Night'),
    ('laser tag', 'Laser Tag'),
    ('get lit', 'Get Lit'),
    ('family skating center', 'Family Skating Center'),
)


class Activity(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order', ]
        verbose_name_plural = 'Activities'

    def __str__(self):
        return self.title


class PartyPackage(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    activity = models.ForeignKey(Activity)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title


class Snack(models.Model):
    snack = models.CharField(choices=snacks, max_length=255)


class Available(models.Model):
    name = models.CharField(max_length=250)
    activity = models.CharField(choices=activities, max_length=255)
    package = models.CharField(max_length=255)
    date_start = models.DateTimeField(auto_created=False)
    date_end = models.DateTimeField(auto_created=False)
    description = models.TextField(default="None")
    snack = models.CharField(max_length=255, choices=snacks, default="Not Shown")
    drink = models.CharField(max_length=255, choices=drinks, default="Not Shown")
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order', ]
        verbose_name_plural = 'Availabilities'

    def __str__(self):
        return self.name

my_site/activities/forms.py
from django import forms

from . import models


class ActivityForm(forms.ModelForm):
    class Meta:
        model = models.Activity
        fields = [
            'title',
            'description',
            'order',
        ]


class PartyPackageForm(forms.ModelForm):
    class Meta:
        model = models.PartyPackage
        fields = [
            'title',
            'description',
            'content',
            'order',
            'activity',
        ]


class AvailableForm(forms.ModelForm):
    class Meta:
        model = models.Available
        fields = [
            'name',
            'activity',
            'package',
            'date_start',
            'date_end',
            'description',
            'snack',
            'drink',
            'order',
        ]

my_site/activities/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, render_to_response

from . import forms
from . import models
# Create your views here.


def availability_page(request):
    items = models.Available.objects.all()
    return render_to_response('availability.html', {'items': items})


def activity_list(request):
    activities = models.Activity.objects.all()
    return render(request, 'activities/activity_list.html', {'activities': activities})


def activity_detail(request, pk):
    activity = get_object_or_404(models.Activity, pk=pk)
    return render(request, 'activities/activity_detail.html', {'activity': activity})


def package_detail(request, activity_pk, package_pk):
    package = get_object_or_404(models.PartyPackage, activity_id=activity_pk, pk=package_pk)
    return render(request, 'activities/package_detail.html', {'package': package})


@login_required
def activity_create(request):
    form = forms.ActivityForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.add_message(request, messages.SUCCESS,
                             "Activity added!")
    context = {
        'form': form
    }

    return render(request, "activities/activity_form.html", context)


@login_required
def availability_create(request):
    form = forms.AvailableForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.add_message(request,  messages.SUCCESS,
                             "Person added!")

    context = {
            'form': form,
    }
    return render(request, "activities/available_form.html", context)


@login_required
def package_create(request):
    form = forms.PartyPackageForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.add_message(request, messages.SUCCESS,
                             "Packageg added!")
    return render(request, "activities/package_form.html", {"form": form})

my_site/activities/templates/activities/activity_detail.html
{% extends "layout.html" %}

{% block title %} {{ activity.title }} {% endblock %}

{% block content %}
    <article>
        <div>
            <h1 class="heading">{{ activity.title }}</h1>
        </div>
        <p class="small-push-right">{{ activity.description }}</p>

        <hr class="hr-line">

        <section class="container_one c_1">
            {% for package in activity.partypackage_set.all %}
                {{ block.super }}
                <ul class="package">
                    <li class="each_link">
                        <a href="{% url 'package' activity_pk=package.activity.pk package_pk=package.pk %}"
                            class="package_links">
                            <h3>
                                {{ package.title }}
                            </h3>
                            {{ package.description }}
                        </a>
                    </li>
                </ul>
            {% endfor %}
        </section>
    </article>

{% endblock %}

my_site/activities/templates/activities/activity_form.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}New Activity{% endblock %}

{% block breadcrumps %}
    <li><a href="{% url 'activity:list' pk=activity.pk %}">{{ activity.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        {{ block.super }}
        <div class="col-md-8">
            <h1 class="heading">A New Activity</h1>
            <hr class="hr-line">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="button" value="Save">
            </form>
            <hr class="hr-line">
            <a href="{% url 'list' %}" class="small-push button">Go to the activity Page</a>
        </div>
    </div>
{% endblock %}

my_site/activities/templates/activities/activity_list.html
{% extends "layout.html" %}

{% block title %}Available Activities{% endblock %}

{% block content %}
    <div class="container_one col-md-8">
        <div class="heading" id="act-list">
                <h1>Activities</h1>
        </div>
        <hr class="hr-line">
        {% for activity in activities %}
            {{  block.super }}
            <ul class="link_hov activity_links small-push"><a href="{% url 'detail' pk=activity.pk %}">
                <li class="each_link" id="each_link2">
                    {{ activity.title }}<br>
                    {{ activity.description }}
                </li>
            </a></ul>
        {% endfor %}
    </div>
{% endblock %}

my_site/activities/templates/activities/activity_nav.html
{% for activity in activities %}
    <li><a href="{% url 'activities:detail' pk=activity.pk %}">{{ activity.title }}</a></li>
{% endfor %}

my_site/activities/templates/activities/available_form.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        {{ block.super }}
        <div class="col-md-8">
            <h1 class="heading">Add Somebody</h1>
            <hr class="hr-line">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="button" value="Save">
            </form>
            <hr class="hr-line">
            <a href="{% url 'availability' %}" class="button small-push">Go the Availability Page</a>
        </div>
    </div>
{% endblock %}

my_site/activities/templates/activities/package_detail.html
{% extends "layout.html" %}
{% load activity_extras %}

{% block title %}{{ package.title }} - {{ package.activity.title }}{% endblock %}

{% block content %}
    <article>
        <h2><a href="{% url 'detail' pk=package.activity.pk %}" class="heading">
            {{ package.activity.title }}
        </a></h2>
        <hr class="hr-line">
        <h3 class="small-push-right">{{ package.title }}</h3>
        {{ package.content|linebreaks }}
    </article>
{% endblock %}

my_site/activities/templates/activities/package_form.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        {{ block.super }}
        <div class="col-md-8">
            <h1 class="heading">Add Package</h1>
            <hr class="hr-line">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="button" value="Save">
            </form>
        </div>
    </div>
{% endblock %}