my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^activities', include('activities.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^reserved/$', views.reserved_view, name='reserved'),
    url(r'^contacts/$', views.contact_page, name='contacts'),
    url(r'^edit_page/$', views.edit_page, name='edit'),
    url(r'^$', views.home_page, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

my_site/my_site/forms.py
from django import forms
from django.core import validators

from activities.models import snacks, drinks, activities


def must_be_empty(value):
    if value:
        raise forms.ValidationError('is not empty')


class ReservedForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Please verify your email address")
    date = forms.DateTimeField(label="Enter your reservation date")
    activity = forms.CharField(
        max_length=25,
        widget=forms.Select(choices=activities),
        label="Activities",
    )
    party_packages = forms.CharField()
    drink = forms.CharField(
        max_length=25,
        widget=forms.Select(choices=drinks),
        label="Drinks",
    )
    snack = forms.CharField(
        max_length=25,
        widget=forms.Select(choices=snacks),
        label="Snacks",
    )
    questions = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label="Do you have any questions for us?",
    )
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="Leave empty",
                               validators=[validators.MaxLengthValidator(0)]
                               )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                "You need to enter the same email in both fields"
            )

my_site/templates/availability.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="heading">Availability</h1>
    <hr class="hr-line">
    {% for x in items %}
        <ul class="small-push-right">
            <li class="small-push"><h2>{{ x.name }} - {{ x.date_start|date:"D d M Y" }}</h2></li>
            <li class="small-push-right li-pads"><strong>Time:</strong>
                {{ x.date_start|date:"P" }} ~ {{ x.date_end|date:"P" }}</li>
            <li class="small-push-right li-pads"><strong>Activity:</strong> {{ x.activity|title }}</li>
            <li class="small-push-right li-pads"><strong>Package:</strong> {{ x.package|title }}</li>
            <li class="small-push-right li-pads"><strong>Snacks:</strong> {{ x.snack|title }}</li>
            <li class="small-push-right li-pads"><strong>Drinks:</strong> {{ x.drink|title }}</li>
            <li class="small-push-right li-pads"><strong>Note:</strong> {{ x.description }}</li>
        </ul>
        <hr class="hr-line">
    {% endfor %}

    {% if user.is_authenticated %}
        <hr class="hr-line">
        <a href="{% url 'create_person' %}" class="button top-small-push">Add Somebody</a>
        <hr class="hr-line">
    {% endif %}

{% endblock %}


my_site/templates/contact_page.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block content %}
    <h1 class="heading">Contacts</h1>
    <div class="row-p">
        <div class="secondary col-p items item-2">
            <h2>Corporate Headquarters</h2>
            <ul class="ul-push">
                <li>Corporate Headquarters</li>
                <li>Family Entertainment Center</li>
                <li>3900 Pleasant Valley Rd,</li>
                <li>Mobile, AL 36609</li>
            </ul>
        </div>

        <div class="tertiary col-p items item-3">
            <h2>General Contact</h2>
            <ul class="ul-push">
                <li>Phone: (251)-382-8024</li>
                <li>Email: familyentertainmentcenter@gmail.com</li>
            </ul>
        </div>

        <div class=" primary-3 col-p items item-1">
            <h2>Get Directions</h2>
            <a class="fig" href="https://www.google.com/maps/@30.6621913,-88.1468619,15z"
                           target="_blank">
            <figure>
                <img class="icon-location" src="{% static 'img/location.svg' %}" alt="location">
                <img class="feat-img tertiary" src="{% static 'img/map.PNG' %}"
                     alt="A Map of Davidson High School">
                    <figcaption>
                            <ul>
                                <li>Family Entertainment Center</li>
                                <li>3900 Pleasant Valley Rd,</li>
                                <li>Mobile, AL 36609</li>
                            </ul>
                    </figcaption>
            </figure>
            </a>
        </div>
    </div>
{% endblock %}

my_site/templates/edit_page.html
{% extends 'layout.html' %}

{% block content %}
{% if user.is_authenticated %}
    <hr class="hr-line">
    <h2 class="heading">Edit Activity</h2>
    <a href="{% url 'create_activity' %}" class="button top-small-push">Add a New Activity</a>
    <a href="{% url 'list' %}" class="small-push button">Go to the activity Page</a>

    <hr class="hr-line">
    <h2 class="heading">Add Person to the Availability Page</h2>
    <a href="{% url 'create_person' %}" class="button top-small-push">Add Somebody</a>
    <a href="{% url 'availability' %}" class="button small-push">Go to the Availability Page</a>

    <hr class="hr-line">
    <h2 class="heading">Edit Package</h2>
    <a href="{% url 'create_package' %}" class="button top-small-push">Add a Package</a>
{% endif %}
{% endblock %}

my_site/templates/home.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Well Hello There{% endblock %}
{% block content %}
    <h1 class="heading small-push">Home</h1>
    <hr class="hr-line">

    <div class="row-p top-small-push">
		<div class="primary-3 col-p">
			<h2>Snacks and Drinks</h2>
            <div class="fix_img">
			    <img class="feat-img" src="{% static 'img/treats.svg' %}" alt="Drinks and eats">
            </div>
			<p>We offered variety of snacks and drinks. The snack we offered are the following:
                Pizzas, Chips, Ice Cream, Donuts, Candies, Cookies, Hot Dogs, Hamburgers.
            </p>
            <p>The drinks we offered are the following:
                Coca Cola, Dr. Pepper, Perpsi, Fanta, Sprite, Apple Juice, Capri Sun.
            </p>
		</div><!--/.primary-->

		<div class="secondary col-p">
			<h2>Welcome!</h2>
			<p>We are a place where family and friends can meet up and have fun.</p>
			<p>We offered a lot of activities from laser tag to get lit to movie night to skating rink.
                It is too much too list all the activities because we have so many activities and all of
                them are fun around friends and families.
            </p>
			<p>We also offered party packages for each activities. Each of them are unique to one another. They will
                make your parties great in a way you never seen before.
            </p>
		</div><!--/.secondary-->

		<div class="tertiary col-p">
			<h2>Our Hours</h2>
            <p>Here is a list of our hours when open during the weekdays and the weekends.</p>
            <ul>
			    <li class="li-pads"><strong>Monday: </strong>8:00 AM - 9:00 PM</li>
			    <li class="li-pads"><strong>Tuesday: </strong>8:00 AM - 9:00 PM</li>
			    <li class="li-pads"><strong>Wednesday: </strong>8:00 AM - 9:00 PM</li>
                <li class="li-pads"><strong>Thursday: </strong>8:00 AM - 9:00 PM</li>
                <li class="li-pads"><strong>Friday: </strong>8:00 AM - 9:00 PM</li>
                <li class="li-pads"><strong>Saturday: </strong>6:00 AM - 10:00 PM</li>
                <li class="li-pads"><strong>Sunday: </strong>1:00 AM - 9:00 PM</li>
            </ul>
		</div><!--/.tertiary-->
	</div>
{% endblock %}

my_site/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
</head>
<body id="body-1">
    <header class="main-header">
        <h1 class="name"><a href="#">Family Entertainment Center</a></h1>
        <ul class="main-nav">
            <li><a href="{% url "home" %}">Home</a></li>
            <li><a href="{% url "list" %}">Activities</a></li>
            <li><a href="{% url "reserved" %}">Reserved Now</a></li>
            <li><a href="{% url "availability" %}">Availability</a></li>
            <li><a href="{% url "contacts" %}">Contact Us</a></li>
            <li>{% if user.is_authenticated %}<a href="{% url 'edit' %}">Edit Site</a>{% endif %}</li>
        </ul>
    </header>

    <div class="banner">
		<img class="logo" src="{% static 'img/logo-iggy.jpg' %}" alt="Family Logo">
		<h1 class="headline">Family Entertainment Center</h1>
		<span class="tagline">The best place to have fun with your family.</span>
	</div><!--/.banner-->

    {% if messages %}
            <div class="row">
                <div class="small-6 small-centered columns">
                    {% for message in messages %}
                        <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

    <div class="site-container">
        {% block content %}{% endblock %}
    </div>

    <footer class="main-footer">
		<div class="footer-inner">
			<span>&copy;2017 The Best Family Entertainment Center Ever.</span>
		</div>
	</footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script>
        $('.datetimeinput').attr('placeholder', '12/28/17 14:30 (Military Time)');
        $('.emailinput').attr('placeholder', 'diegosalas00@hotmail.com');
        $('#id_name').attr('placeholder', 'Diego Salas');
        $('#id_party_packages').attr('placeholder', 'eg. 16 Player Party Package');
        $('#id_questions').attr('placeholder', "Hi! I'm Diego. Please feel free to ask any questions " +
            "about us, the activities, or the party packages.");

    </script>
    <script src="{% static "js/app.js" %}"></script>
</body>
</html>

my_site/templates/reserved_form.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block title %}Reserved Now{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="heading">
                <h1>Reserved Now</h1>
            </div>
            <hr class="hr-line">
            <form action="" method="POST" class="small-push">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Submit" class="button">
            </form>
        </div>
    </div>
{% endblock %}